default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ncct_app_development

test:
  <<: *default
  database: ncct_app_test

production:
  adapter: postgresql
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    database: ncct_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: ncct_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: ncct_app_production_cable
    migrations_paths: db/cable_migrate
